#docker-compose.yml

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - sqlserver
    env_file:
      - ./backend/.env
    restart: always
  frontend:
    build: 
      context: ./frontend
      args: 
        VITE_API_URL: http://backend:5000
    ports: 
      - "5173:80" 
    depends_on:
      - backend 
  redis:
    image: redis
    ports:
      - "6379:6379"
 
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - SA_PASSWORD=103395Dat
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "103395Dat", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5
   
volumes:
  sql_data:
